# Generated by Django 4.2.27 on 2026-05-02 22:51

from django.db import migrations, models


def forwards_copy_fk_to_through(apps, schema_editor):
    Product = apps.get_model("core", "Product")
    ProductBrand = apps.get_model("core", "ProductBrand")
    ProductCategory = apps.get_model("core", "ProductCategory")
    ProductSize = apps.get_model("core", "ProductSize")
    for p in Product.objects.all():
        if getattr(p, "brand_id", None):
            ProductBrand.objects.get_or_create(
                product_id=p.pk, brand_id=p.brand_id,
            )
        if getattr(p, "category_id", None):
            ProductCategory.objects.get_or_create(
                product_id=p.pk, category_id=p.category_id,
            )
        if getattr(p, "size_id", None):
            ProductSize.objects.get_or_create(
                product_id=p.pk, size_id=p.size_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RunPython(forwards_copy_fk_to_through, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='brands',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.ProductBrand', to='core.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.ProductCategory', to='core.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='+', through='core.ProductSize', to='core.size'),
        ),
        migrations.AddConstraint(
            model_name='productbrand',
            constraint=models.UniqueConstraint(fields=('product', 'brand'), name='uniq_core_productbrand_product_brand'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('product', 'category'), name='uniq_core_productcategory_product_category'),
        ),
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.UniqueConstraint(fields=('product', 'size'), name='uniq_core_productsize_product_size'),
        ),
    ]
