# Generated by Django 4.2.27 on 2026-05-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_brand_fk_drop_productbrand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productuser',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productuser',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренды', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товары', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размеры', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='ProductUser',
        ),
    ]
