# Generated by Django 4.2.27 on 2026-05-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tag_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='+', to='core.tag'),
        ),
    ]
