# Generated by Django 4.2.27 on 2026-05-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(related_name='+', to='core.product'),
        ),
    ]
