# Generated by Django 4.2.27 on 2026-05-10 14:04

from django.db import migrations, models
import django.db.models.deletion


def copy_product_tags_from_old_table(apps, schema_editor):
    ProductTag = apps.get_model("core", "ProductTag")
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT product_id, tag_id FROM core_product_tags")
        for product_id, tag_id in cursor.fetchall():
            if product_id is None or tag_id is None:
                continue
            ProductTag.objects.get_or_create(product_id=product_id, tag_id=tag_id)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_product_options_remove_tag_products_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_links",
                        to="core.product",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_links",
                        to="core.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначенный тег",
                "verbose_name_plural": "Назначенные теги",
                "unique_together": {("product", "tag")},
            },
        ),
        migrations.RunPython(copy_product_tags_from_old_table, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="+", through="core.ProductTag", to="core.tag"),
        ),
    ]
