# Generated by Django 4.2.27 on 2026-05-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_product_tag_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avito_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
